# Generated by Django 4.2.1 on 2023-05-09 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comments", "0002_comment_is_okay_likecomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likecomment",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="comments.comment",
            ),
        ),
        migrations.AlterField(
            model_name="likecomment",
            name="like_type",
            field=models.CharField(
                choices=[("L", "Like"), ("D", "Dislike")], default="L", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="likecomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="likecomment",
            unique_together={("user", "comment")},
        ),
    ]
