# Generated by Django 4.2.1 on 2023-05-18 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_rename_user_id_subscribe_profile_id"),
        ("comments", "0002_remove_comment_user_comment_profile"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="likecomment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="likecomment",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="members.profile",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="likecomment",
            unique_together={("profile", "comment")},
        ),
        migrations.RemoveField(
            model_name="likecomment",
            name="user",
        ),
    ]
