# Generated by Django 4.2.1 on 2023-05-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_list",
            name="user_list_type",
            field=models.CharField(
                choices=[("F", "Favorites"), ("W", "Watchlist"), ("B", "Bookmark")],
                default="F",
                max_length=1,
            ),
        ),
        migrations.DeleteModel(
            name="List_movie",
        ),
    ]
