# Generated by Django 4.2.1 on 2023-05-09 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0011_movie_country"),
        ("members", "0010_remove_profile_bookmark_list_and_more"),
        ("lists", "0002_alter_user_list_user_list_type_delete_list_movie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Watchedlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watched_list",
                        to="members.profile",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="User_list",
        ),
    ]
