# Generated by Django 4.2 on 2023-04-08 11:00

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to=movies.models.news_thumbnail_path)),
                ('photo', models.ImageField(upload_to=movies.models.news_photo_path)),
                ('description', models.TextField()),
                ('actors', models.ManyToManyField(to='movies.actor')),
                ('directors', models.ManyToManyField(to='movies.director')),
                ('movies', models.ManyToManyField(to='movies.movie')),
            ],
        ),
    ]
