# Generated by Django 4.2 on 2023-04-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='actors',
            field=models.ManyToManyField(blank=True, to='movies.actor'),
        ),
        migrations.AlterField(
            model_name='news',
            name='directors',
            field=models.ManyToManyField(blank=True, to='movies.director'),
        ),
        migrations.AlterField(
            model_name='news',
            name='movies',
            field=models.ManyToManyField(blank=True, to='movies.movie'),
        ),
    ]
