# Generated by Django 4.2.1 on 2023-05-21 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_rename_user_id_subscribe_profile_id"),
        ("movies", "0002_news_publish_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="user",
        ),
        migrations.AddField(
            model_name="rating",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.profile",
            ),
            preserve_default=False,
        ),
    ]
