# Generated by Django 4.2 on 2023-04-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_news_m2m_fields_blank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='last_name',
        ),
    ]
