# Generated by Django 4.2.1 on 2023-05-26 19:28

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_remove_rating_user_rating_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="series_episode",
            name="description",
        ),
        migrations.RemoveField(
            model_name="series_season",
            name="description",
        ),
        migrations.RemoveField(
            model_name="series_season",
            name="publish_date",
        ),
        migrations.AddField(
            model_name="series_episode",
            name="photo",
            field=models.ImageField(
                null=True, upload_to=movies.models.episode_photo_path
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="movies",
            field=models.ManyToManyField(
                blank=True, related_name="category_set", to="movies.movie"
            ),
        ),
    ]
