# Generated by Django 4.2.1 on 2023-07-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_alter_rating_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="imdb_link",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="director",
            name="imdb_link",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
