# Generated by Django 4.2 on 2023-04-11 13:55

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_first_name_director_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.ImageField(upload_to=movies.models.movie_actor_path),
        ),
        migrations.DeleteModel(
            name='Movie_meta',
        ),
    ]
