# Generated by Django 4.2.1 on 2023-05-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0010_series_episode_episode_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="country",
            field=models.CharField(default="USA", max_length=255),
            preserve_default=False,
        ),
    ]
