# Generated by Django 4.2 on 2023-04-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_follows'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Profile',
        ),
    ]
