# Generated by Django 4.2.1 on 2023-05-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_rename_created_userfollow_created_at_subscribe"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
