# Generated by Django 4.2.1 on 2023-05-12 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_post_is_premium"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscribe",
            old_name="user_id",
            new_name="profile_id",
        ),
    ]
