# Generated by Django 4.2.1 on 2023-05-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_rename_user_id_subscribe_profile_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subscribe",
            unique_together={("profile_id", "subscriber_id")},
        ),
        migrations.AlterUniqueTogether(
            name="userfollow",
            unique_together={("follower_id", "following_id")},
        ),
    ]
