# Generated by Django 4.2 on 2023-05-09 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_remove_profile_follows_userfollow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfollow",
            name="follower_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followings",
                to="members.profile",
            ),
        ),
        migrations.AlterField(
            model_name="userfollow",
            name="following_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to="members.profile",
            ),
        ),
    ]
