# Generated by Django 4.2.1 on 2023-05-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0011_movie_country"),
        ("members", "0008_remove_profile_bio_remove_profile_birth_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bookmark_list",
            field=models.ManyToManyField(
                blank=True, related_name="profile_bookmark_list", to="movies.movie"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="favourites_list",
            field=models.ManyToManyField(
                blank=True, related_name="profile_favourites_list", to="movies.movie"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="watched_list",
            field=models.ManyToManyField(
                blank=True, related_name="profile_watched_list", to="movies.movie"
            ),
        ),
    ]
