# Generated by Django 4.2.1 on 2023-05-09 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0009_remove_profile_bio_remove_profile_birth_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bookmark_list",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="favourites_list",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="watched_list",
        ),
    ]
